# Generated by Django 3.2.3 on 2021-07-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='taking_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
